###
    GET http://localhost:1234/movies
  
###
  POST http://localhost:1234/movies
  Content-Type: application/json

  {
      "title": "Avengers : Endgame",
      "year": 2019,
      "director": "Joss Whedon",
      "duration": 142,
      "poster": "https://m.media-amazon.com/images/I/71niXI3lxlL._AC_SL1183_.jpg",
      "genre": ["Action", "Adventure", "Sci-Fi" ]
    }



###
    GET http://localhost:1234/movies?genre=Drama
    
###
    GET http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### Actualizar pelicula
    PATCH http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
    Content-Type: application/json

    {
      "year": 2005
    }