  ###
    GET http://localhost:1234/movies
  
  ###
  POST http://localhost:1234/movies
  Content-Type: application/json

  {
      "title": "The Godfather",
      "year": 1972,
      "direct+or": "Francis Ford Coppola",
      "duration": 175,
      "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
      "genre": ["Crime", "Drama"]
    }



###
    GET http://localhost:1234/movies?genre=Drama
    
###
    GET http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### Actualizar pelicula
    PATCH http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
    Content-Type: application/json

    {
      "year": 2005
    }